### This is a project to Determine a student Final's Grade

In [17]:
# These are the imports
import pandas as pd
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score

In [18]:
df = pd.read_csv('student-por-new.csv')
df.head()

,school,sex,age,address,famsize,Pstatus,Medu,Fedu,Mjob,Fjob,...,famrel,freetime,goout,Dalc,Walc,health,absences,G1,G2,G3
0,GP,F,18,U,GT3,A,4,4,at_home,teacher,...,4,3,4,1,1,3,4,0,11,11
1,GP,F,17,U,GT3,T,1,1,at_home,other,...,5,3,3,1,1,3,2,9,11,11
2,GP,F,15,U,LE3,T,1,1,at_home,other,...,4,3,2,2,3,3,6,12,13,12
3,GP,F,15,U,GT3,T,4,2,health,services,...,3,2,2,1,1,5,0,14,14,14
4,GP,F,16,U,GT3,T,3,3,other,other,...,4,3,2,1,2,5,0,11,13,13

In [19]:
df.shape

(649, 33)

In [20]:
print(df.columns)

Index(['school', 'sex', 'age', 'address', 'famsize', 'Pstatus', 'Medu', 'Fedu',
       'Mjob', 'Fjob', 'reason', 'guardian', 'traveltime', 'studytime',
       'failures', 'schoolsup', 'famsup', 'paid', 'activities', 'nursery',
       'higher', 'internet', 'romantic', 'famrel', 'freetime', 'goout', 'Dalc',
       'Walc', 'health', 'absences', 'G1', 'G2', 'G3'],
      dtype='object')

In [21]:
df.dtypes

school        object
sex           object
age            int64
address       object
famsize       object
Pstatus       object
Medu           int64
Fedu           int64
Mjob          object
Fjob          object
reason        object
guardian      object
traveltime     int64
studytime      int64
failures       int64
schoolsup     object
famsup        object
paid          object
activities    object
nursery       object
higher        object
internet      object
romantic      object
famrel         int64
freetime       int64
goout          int64
Dalc           int64
Walc           int64
health         int64
absences       int64
G1             int64
G2             int64
G3             int64
dtype: object

In [22]:
# Let use only the columns that we need
X = df.drop(['G3'], axis=1)
y = df['G3' ]

# This will split the data
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state = 42)

### Cleaning data

In [23]:
# This encode the categorical variables to numericals

df = pd.get_dummies(df, drop_first=True)

df.head(40)

,age,Medu,Fedu,traveltime,studytime,failures,famrel,freetime,goout,Dalc,...,guardian_mother,guardian_other,schoolsup_yes,famsup_yes,paid_yes,activities_yes,nursery_yes,higher_yes,internet_yes,romantic_yes
0,18,4,4,2,2,0,4,3,4,1,...,1,0,1,0,0,0,1,1,0,0
1,17,1,1,1,2,0,5,3,3,1,...,0,0,0,1,0,0,0,1,1,0
2,15,1,1,1,2,0,4,3,2,2,...,1,0,1,0,0,0,1,1,1,0
3,15,4,2,1,3,0,3,2,2,1,...,1,0,0,1,0,1,1,1,1,1
4,16,3,3,1,2,0,4,3,2,1,...,0,0,0,1,0,0,1,1,0,0
5,16,4,3,1,2,0,5,4,2,1,...,1,0,0,1,0,1,1,1,1,0
6,16,2,2,1,2,0,4,4,4,1,...,1,0,0,0,0,0,1,1,1,0
7,17,4,4,2,2,0,4,1,4,1,...,1,0,1,1,0,0,1,1,0,0
8,15,3,2,1,2,0,4,2,2,1,...,1,0,0,1,0,0,1,1,1,0
9,15,3,4,1,2,0,5,5,1,1,...,1,0,0,1,0,1,1,1,1,0
10,15,4,4,1,2,0,3,3,3,1,...,1,0,0,1,0,0,1,1,1,0
11,15,2,1,3,3,0,5,2,2,1,...,0,0,0,1,0,1,1,1,1,0
12,15,4,4,1,1,0,4,3,3,1,...,0,0,0,1,0,1,1,1,1,0
13,15,4,3,2,2,0,5,4,3,1,...,1,0,0,1,0,0,1,1,1,0
14,15,2,2,1,3,0,4,5,2,1,...,0,1,0,1,0,0,1,1,1,1
15,16,4,4,1,1,0,4,4,4,1,...,1,0,0,1,0,0,1,1,1,0
16,16,4,4,1,3,0,3,2,3,1,...,1,0,0,1,0,1,1,1,1,0
17,16,3,3,3,2,0,5,3,2,1,...,1,0,1,1,0,1,1,1,0,0
18,17,3,2,1,1,3,5,5,5,2,...,1,0,0,1,1,1,1,1,1,0
19,16,4,3,1,1,0,3,1,3,1,...,0,0,0,0,0,1,1,1,1,0
20,15,4,3,1,2,0,4,4,1,1,...,1,0,0,0,0,0,1,1,1,0
21,15,4,4,1,1,0,5,4,2,1,...,0,0,0,1,1,0,1,1,1,0
22,16,4,2,1,2,0,4,5,1,1,...,1,0,0,0,0,1,1,1,1,0
23,16,2,2,2,2,0,5,4,4,2,...,1,0,0,1,0,1,1,1,1,0
24,15,2,4,1,3,0,4,3,2,1,...,1,0,1,1,0,1,1,1,1,0
25,16,2,2,1,1,0,1,2,2,1,...,1,0,0,1,0,0,0,1,1,0
26,15,2,2,1,1,0,4,2,2,1,...,1,0,0,1,0,0,1,1,1,0
27,15,4,2,1,1,0,2,2,4,2,...,1,0,0,0,0,0,1,1,1,0
28,16,3,4,1,2,0,5,3,3,1,...,1,0,1,1,1,1,1,1,1,0
29,16,4,4,1,2,0,4,4,5,5,...,1,0,0,1,1,1,1,1,1,1
30,15,4,4,1,2,0,5,4,2,3,...,1,0,0,1,1,0,0,1,1,0
31,15,4,4,2,2,0,4,3,1,1,...,1,0,0,1,0,1,1,1,1,0
32,15,4,3,1,2,0,4,5,2,1,...,1,0,0,1,0,1,1,1,1,1
33,15,3,3,1,2,0,5,3,2,1,...,1,0,0,0,0,1,0,1,1,0
34,16,3,2,1,1,0,5,4,3,1,...,1,0,0,1,0,0,0,1,1,0
35,15,2,3,2,1,0,3,5,1,1,...,0,0,0,1,0,1,1,1,0,0
36,15,4,3,1,3,0,5,4,3,1,...,1,0,0,1,0,1,1,1,1,0
37,16,4,4,2,3,0,2,4,3,1,...,1,0,0,1,0,1,1,1,1,1
38,15,3,4,1,3,0,4,3,2,1,...,1,0,1,1,0,1,1,1,1,0
39,15,2,2,1,1,0,4,3,1,1,...,1,0,1,1,0,1,1,1,0,0

### Trainning the model

In [24]:
regr = LinearRegression()
regr.fit(X_train, y_train)

ValueError: could not convert string to float: 'GP'

In [ ]:
### Make prediction

In [ ]:
y_pred = regr.predict(X_test)

### This evaluate the model

In [ ]:
mse = mean_squared_error(y_test, y_pred)
r2 = r2_score(y_test, y_pred)

print(f"Mean Squared Error: {mse}")
print(f"R-squared value: {r2}")